name: Run Pester Tests

on:
  push:
    branches:
      - main
      - master
      - '**'
  pull_request:
    branches:
      - main
      - '**'

jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PowerShell
        uses: actions/setup-powershell@v2

      - name: Install Pester
        run: pwsh -Command "Install-Module -Name Pester -Force -Scope CurrentUser"

      - name: Run Pester tests
        run: pwsh -Command "Invoke-Pester -Path ./Tests -Output Detailed"
